// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EmailTemplatesCore.Models
{

    // EmailTemplateType
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.30.0.0")]
    public class EmailTemplateType
    {
        [Column(@"Id", Order = 1, TypeName = "int")]
        [Required]
        [Key]
        [Display(Name = "Id")]
        public int Id { get; set; } // Id (Primary key)

        [Required]
        [MaxLength(100)]
        [StringLength(100)]
        [Display(Name = "Key")]
        public string Key { get; set; } // KEY (length: 100)

        [Required]
        [MaxLength(150)]
        [StringLength(150)]
        [Display(Name = "Name")]
        public string Name { get; set; } // Name (length: 150)

        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "Created by")]
        public string CreatedBy { get; set; } // CreatedBy (length: 50)

        [Display(Name = "Created on")]
        public System.DateTime? CreatedOn { get; set; } // CreatedOn

        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "Modified by")]
        public string ModifiedBy { get; set; } // ModifiedBy (length: 50)

        [Display(Name = "Modified on")]
        public System.DateTime? ModifiedOn { get; set; } // ModifiedOn

        // Reverse navigation

        /// <summary>
        /// Child EmailTemplates where [EmailTemplate].[TypeId] point to this entity (EmailTemplateType_ID_EmailTemplate_TypeId)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<EmailTemplate> EmailTemplates { get; set; } // EmailTemplate.EmailTemplateType_ID_EmailTemplate_TypeId

        public EmailTemplateType()
        {
            EmailTemplates = new System.Collections.Generic.List<EmailTemplate>();
        }
    }

}
// </auto-generated>
