// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EmailTemplatesCore.Models
{

    // EmailMessageToSend
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.30.0.0")]
    public class EmailMessageToSend
    {
        [Column(@"Id", Order = 1, TypeName = "int")]
        [Required]
        [Key]
        [Display(Name = "Id")]
        public int Id { get; set; } // Id (Primary key)

        [Required]
        [Display(Name = "Template ID")]
        public int TemplateId { get; set; } // TemplateId

        [Required]
        [Display(Name = "Data")]
        public string Data { get; set; } // Data

        [Required]
        [MaxLength(150)]
        [StringLength(150)]
        [Display(Name = "Email to")]
        public string EmailTo { get; set; } // EmailTo (length: 150)

        [Display(Name = "Sent on")]
        public System.DateTime? SentOn { get; set; } // SentOn

        [Display(Name = "Sent")]
        public bool? Sent { get; set; } // Sent

        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "Created by")]
        public string CreatedBy { get; set; } // CreatedBy (length: 50)

        [Display(Name = "Created on")]
        public System.DateTime? CreatedOn { get; set; } // CreatedOn

        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "Modified by")]
        public string ModifiedBy { get; set; } // ModifiedBy (length: 50)

        [Display(Name = "Modified on")]
        public System.DateTime? ModifiedOn { get; set; } // ModifiedOn

        // Foreign keys

        /// <summary>
        /// Parent EmailTemplate pointed by [EmailMessageToSend].([TemplateId]) (EmailTemplate_Id_EmailMessageToSend_TemplateId)
        /// </summary>
        public virtual EmailTemplate EmailTemplate { get; set; } // EmailTemplate_Id_EmailMessageToSend_TemplateId
    }

}
// </auto-generated>
