#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using EmailTemplatesCore;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/EmailTemplates/_Template.cshtml")]
    public partial class _Views_EmailTemplates__Template_cshtml : System.Web.Mvc.WebViewPage<EmailTemplatesCore.ViewModels.EmailTemplateViewModel>
    {
        public _Views_EmailTemplates__Template_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\EmailTemplates\_Template.cshtml"
Write(Html.HiddenFor(o => o.Id));

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("    ");

            
            #line 4 "..\..\Views\EmailTemplates\_Template.cshtml"
Write(Html.LabelFor(o => o.Subject, new { @class = "control-label col-sm-4" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <div");

WriteLiteral(" class=\"col-sm-8\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 6 "..\..\Views\EmailTemplates\_Template.cshtml"
   Write(Html.TextBoxFor(o => o.Subject, new { @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 7 "..\..\Views\EmailTemplates\_Template.cshtml"
   Write(Html.ValidationMessageFor(o => o.Subject));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n</div>\r\n\r\n<div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("    ");

            
            #line 12 "..\..\Views\EmailTemplates\_Template.cshtml"
Write(Html.LabelFor(o => o.From, new { @class = "control-label col-sm-4" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <div");

WriteLiteral(" class=\"col-sm-8\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 14 "..\..\Views\EmailTemplates\_Template.cshtml"
   Write(Html.TextBoxFor(o => o.From, new { @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 15 "..\..\Views\EmailTemplates\_Template.cshtml"
   Write(Html.ValidationMessageFor(o => o.From));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n</div>\r\n\r\n<div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("    ");

            
            #line 20 "..\..\Views\EmailTemplates\_Template.cshtml"
Write(Html.LabelFor(o => o.Template, new { @class = "control-label col-sm-4" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <div");

WriteLiteral(" class=\"col-sm-8\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 22 "..\..\Views\EmailTemplates\_Template.cshtml"
   Write(Html.TextAreaFor(o => o.Template, new { @class = "form-control mceEditor" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 23 "..\..\Views\EmailTemplates\_Template.cshtml"
   Write(Html.ValidationMessageFor(o => o.Template));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
