#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using EmailTemplatesCore;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/EmailTemplates/EditEmailTemplate.cshtml")]
    public partial class _Views_EmailTemplates_EditEmailTemplate_cshtml : System.Web.Mvc.WebViewPage<EmailTemplatesCore.ViewModels.EmailTemplateViewModel>
    {
        public _Views_EmailTemplates_EditEmailTemplate_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"panel panel-default\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"panel-heading\"");

WriteLiteral(">\r\n        Edit Email template\r\n    </div>\r\n");

            
            #line 8 "..\..\Views\EmailTemplates\EditEmailTemplate.cshtml"
    
            
            #line default
            #line hidden
            
            #line 8 "..\..\Views\EmailTemplates\EditEmailTemplate.cshtml"
     using (Html.BeginForm())
    {
        
            
            #line default
            #line hidden
            
            #line 10 "..\..\Views\EmailTemplates\EditEmailTemplate.cshtml"
   Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 10 "..\..\Views\EmailTemplates\EditEmailTemplate.cshtml"
                                

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"form-horizontal\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 12 "..\..\Views\EmailTemplates\EditEmailTemplate.cshtml"
       Write(Html.HiddenFor(o => o.typeId));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 13 "..\..\Views\EmailTemplates\EditEmailTemplate.cshtml"
       Write(Html.Partial("_Template", Model));

            
            #line default
            #line hidden
WriteLiteral("\r\n            <div");

WriteLiteral(" class=\"form-group text-center\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-primary\"");

WriteLiteral(">Save</button>\r\n            </div>\r\n        </div>\r\n");

            
            #line 18 "..\..\Views\EmailTemplates\EditEmailTemplate.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</div>");

        }
    }
}
#pragma warning restore 1591
