#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    
    #line 1 "..\..\Views\EmailTemplates\ViewCurrentEmailTemplates.cshtml"
    using System.Data.Entity.ModelConfiguration.Configuration;
    
    #line default
    #line hidden
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using EmailTemplatesCore;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/EmailTemplates/ViewCurrentEmailTemplates.cshtml")]
    public partial class _Views_EmailTemplates_ViewCurrentEmailTemplates_cshtml : System.Web.Mvc.WebViewPage<List<EmailTemplatesCore.ViewModels.EmailTemplateViewModel>>
    {
        public _Views_EmailTemplates_ViewCurrentEmailTemplates_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\EmailTemplates\ViewCurrentEmailTemplates.cshtml"
  
    ViewBag.Title = "View Current Email Templates";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"col-sm-4\"");

WriteLiteral(">\r\n        <h2>View Current Email Templates</h2>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"col-sm-4 col-sm-offset-4\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 12 "..\..\Views\EmailTemplates\ViewCurrentEmailTemplates.cshtml"
   Write(Html.ActionLink("Add Template", "AddEmailTemplate", "EmailTemplates", null, new {@class= "btn btn-primary"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n</div>\r\n<div");

WriteLiteral(" class=\"table-responsive\"");

WriteLiteral(">\r\n    <table");

WriteLiteral(" class=\"table table-striped\"");

WriteLiteral(@">
        <thead>
            <tr>
                <th>
                    Type
                </th>
                <th>
                    From
                </th>
                <th>
                    Created On
                </th>
                <th> &nbsp; </th>
            </tr>
        </thead>
        <tbody>
");

            
            #line 32 "..\..\Views\EmailTemplates\ViewCurrentEmailTemplates.cshtml"
            
            
            #line default
            #line hidden
            
            #line 32 "..\..\Views\EmailTemplates\ViewCurrentEmailTemplates.cshtml"
             foreach (var item in Model)
            {

            
            #line default
            #line hidden
WriteLiteral("                <tr>\r\n                    <td>\r\n");

WriteLiteral("                        ");

            
            #line 36 "..\..\Views\EmailTemplates\ViewCurrentEmailTemplates.cshtml"
                   Write(item.Name);

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </td>\r\n                    <td>\r\n");

WriteLiteral("                        ");

            
            #line 39 "..\..\Views\EmailTemplates\ViewCurrentEmailTemplates.cshtml"
                   Write(item.From);

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </td>\r\n                    <td>\r\n");

WriteLiteral("                        ");

            
            #line 42 "..\..\Views\EmailTemplates\ViewCurrentEmailTemplates.cshtml"
                   Write(item.CreatedOn);

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </td>\r\n                    <td>\r\n");

WriteLiteral("                        ");

            
            #line 45 "..\..\Views\EmailTemplates\ViewCurrentEmailTemplates.cshtml"
                   Write(Html.ActionLink("Edit Template", "EditEmailTemplate", "EmailTemplates", new { id = item.Id }, new { @class = "btn btn-primary" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 46 "..\..\Views\EmailTemplates\ViewCurrentEmailTemplates.cshtml"
                   Write(Html.ActionLink("Test Template", "TestEmailTemplate", "EmailTemplates", new { id = item.Id }, new { @class = "btn btn-primary" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </td>\r\n                </tr>\r\n");

            
            #line 49 "..\..\Views\EmailTemplates\ViewCurrentEmailTemplates.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </tbody>\r\n    </table>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
